# Generated by Django 3.2.5 on 2023-12-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Authors',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
