# Generated by Django 3.2.5 on 2023-12-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apisapp', '0002_auto_20231229_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authors',
        ),
    ]
