# Generated by Django 3.2.5 on 2023-12-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apisapp', '0003_rename_author_books_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='authors',
            new_name='author',
        ),
    ]
