# Generated by Django 3.2.5 on 2023-12-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apisapp', '0004_rename_authors_books_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
